
function createfigurePorcentagem(YMatrix1,name)
%CREATEFIGURE1(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Dec-2016 18:35:18

% Create figure
figure1 = figure;
set(figure1, 'Position', [1 1 2000 1000])
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.116071428571429 0.103448275862069 0.78892857142857 0.821551724137931]);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(YMatrix1,'Parent',axes1);
set(bar1(1),'DisplayName','Reference');
set(bar1(2),'DisplayName','EM EM');
set(bar1(3),'DisplayName','EM FCM');
set(bar1(4),'DisplayName','EM ISO');
set(bar1(5),'DisplayName','EM KM');
set(bar1(6),'DisplayName','FCM EM');
set(bar1(7),'DisplayName','FCM FCM');
set(bar1(8),'DisplayName','FCM ISO');
set(bar1(9),'DisplayName','FCM KM');
set(bar1(10),'DisplayName','KM EM');
set(bar1(11),'DisplayName','KM FCM');
set(bar1(12),'DisplayName','KM ISO');
set(bar1(13),'DisplayName','KM KM');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',14,'XTick',...
    [0.5 1 2 3 4 5],'XTickLabel',...
    {'','Forest','class20','class30','class40','class50'},'YGrid',...
    'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');
saveas(figure1,name)
